meta_title: "Office Notarial Perraut - Pirioux - Mével"
meta_description: "Notre étude est une étude généraliste avec des savoir-faire spécialisés. Composée de trois notaires et d’une vingtaine de collaborateurs, sa taille humaine permet un véritable travail d’équipe aussi bien au niveau des collaborateurs que des notaires eux-mêmes."
meta_image: "banner-home.jpg"
# twitter_account: "@nomdevotrecompte"
