meta_title: "Notaires Rennes | Office Perraut - Pirioux - Mével"
meta_description: "Trois notaires et une vingtaine de collaborateurs vous accompagnent dans vos démarches. Notre étude est une étude généraliste avec des savoir-faire spécialisés."
meta_image: "notaires-rennes-perraut-pirioux-mevel.jpg"
# twitter_account: "@nomdevotrecompte"
